"""The rules file is the first time remem writes context into the user's
working tree rather than into a stream, so the policy around it is tested,
not assumed."""

from __future__ import annotations

from pathlib import Path

from remem.agents.cursor import rules
from remem.agents.cursor.adapter import ROOT_KEY, CursorAdapter

EXCLUDE_LINE = ".cursor/rules/remem.mdc"


def test_the_rendered_file_always_applies():
    out = rules.render("some knowledge")

    assert out.startswith("---\n")
    assert "alwaysApply: true" in out
    assert "some knowledge" in out


def test_the_rendered_file_says_it_is_generated():
    assert "generated by remem" in rules.render("x")


def test_writing_creates_the_rules_directory(tmp_path):
    path = rules.write(tmp_path, "hello")

    assert path == tmp_path / ".cursor" / "rules" / "remem.mdc"
    assert "hello" in path.read_text()


def test_writing_overwrites_unconditionally(tmp_path):
    """Machine-owned, like opencode's remem.js. A user who wants local
    edits here is asking for the wrong file."""
    rules.write(tmp_path, "first")

    path = rules.write(tmp_path, "second")

    assert "first" not in path.read_text()
    assert "second" in path.read_text()


def test_exclude_appends_to_git_info_exclude(tmp_path):
    (tmp_path / ".git" / "info").mkdir(parents=True)

    added = rules.exclude(tmp_path)

    assert added is True
    assert EXCLUDE_LINE in (tmp_path / ".git" / "info" / "exclude").read_text()


def test_exclude_is_idempotent(tmp_path):
    (tmp_path / ".git" / "info").mkdir(parents=True)
    rules.exclude(tmp_path)

    added = rules.exclude(tmp_path)

    assert added is False
    text = (tmp_path / ".git" / "info" / "exclude").read_text()
    assert text.count(EXCLUDE_LINE) == 1


def test_exclude_preserves_what_is_already_there(tmp_path):
    info = tmp_path / ".git" / "info"
    info.mkdir(parents=True)
    (info / "exclude").write_text("# existing\n*.log\n")

    rules.exclude(tmp_path)

    text = (info / "exclude").read_text()
    assert "*.log" in text and EXCLUDE_LINE in text


def test_exclude_outside_a_repository_is_not_an_error(tmp_path):
    """A workspace outside a repository is an ordinary thing, not a
    failure."""
    assert rules.exclude(tmp_path) is False


def test_inject_writes_the_block_and_returns_the_path(tmp_path):
    adapter = CursorAdapter()

    path = adapter.inject("the block", {ROOT_KEY: str(tmp_path)})

    assert path == str(tmp_path / ".cursor" / "rules" / "remem.mdc")
    assert "the block" in Path(path).read_text()


def test_inject_without_a_root_writes_nothing(tmp_path):
    adapter = CursorAdapter()

    assert adapter.inject("the block", {}) is None


def test_inject_of_an_empty_block_writes_nothing(tmp_path):
    """An empty block means no knowledge base matched. Writing an empty
    rules file would hand Cursor a rule that says nothing, every session."""
    adapter = CursorAdapter()

    assert adapter.inject("", {ROOT_KEY: str(tmp_path)}) is None
    assert not (tmp_path / ".cursor").exists()
