"""Writing the plugin, and overwriting it.

remem owns plugin.js: no version marker, no merge, no prompt. The file is
machine-generated and machine-replaced, and the install says where it went.
"""

from __future__ import annotations

import psycopg
import pytest

from remem.agents.base import UnsupportedScope
from remem.agents.opencode.adapter import OpenCodeAdapter
from remem.backends.postgres.migrate import migrate


@pytest.fixture
def env(live_dsn, tmp_path):
    """A real, migrated database for install() to round-trip through.

    Every test below except the unknown-scope one calls install(), and
    install() now folds verify()'s live database round-trip into its report
    (Task 6) - the same reason tests/test_claude_code_install.py's install
    tests carry `db`. Passing env={} instead, as this file used to, does not
    skip that round-trip: config.load(env={}) does not fall back to
    os.environ, so it would resolve the DSN to whatever real Postgres the
    developer happens to have at the default address and quietly write and
    delete rows there.
    """
    with psycopg.connect(live_dsn) as c:
        migrate(c)
        c.commit()
    return {
        "REMEM_DSN": live_dsn,
        "REMEM_USER_ID": "brandon",
        "REMEM_CONFIG": str(tmp_path / "none.toml"),
    }


@pytest.mark.db
def test_user_scope_writes_the_plugin_under_the_config_directory(tmp_path, env):
    report = OpenCodeAdapter().install(scope="user", home=tmp_path, env=env)

    plugin = tmp_path / ".config" / "opencode" / "plugin" / "remem.js"
    assert plugin.exists()
    assert plugin.read_text().startswith("// generated by remem - do not edit")
    assert any(str(plugin) in action for action in report.actions)


@pytest.mark.db
def test_project_scope_writes_beside_the_repository(tmp_path, monkeypatch, env):
    monkeypatch.chdir(tmp_path)

    OpenCodeAdapter().install(scope="project", home=tmp_path, env=env)

    assert (tmp_path / ".opencode" / "plugin" / "remem.js").exists()


@pytest.mark.db
def test_project_scope_from_a_subdirectory_writes_at_the_repository_root(
    tmp_path, monkeypatch, env
):
    """CT-2: a project-scoped install used to resolve the plugin directory
    from raw `Path.cwd()`, so running it from a subdirectory wrote
    `<subdir>/.opencode/plugin/remem.js` - a location opencode, which scans
    from the repository root, never loads. `identity()` already resolves
    writes through the git common directory for exactly this reason; the
    install path has to agree with it."""
    import subprocess

    repo = tmp_path / "repo"
    subdir = repo / "src" / "nested"
    subdir.mkdir(parents=True)
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    monkeypatch.chdir(subdir)

    OpenCodeAdapter().install(scope="project", home=tmp_path, env=env)

    assert (repo / ".opencode" / "plugin" / "remem.js").exists()
    assert not (subdir / ".opencode").exists()


def test_an_unknown_scope_refuses_rather_than_guessing(tmp_path):
    """UnsupportedScope over a fallback: an install that reports success
    while having written somewhere else is worse than one that refuses.

    No `db` marker: plugin_dir() raises before install() ever calls
    verify(), so this test never touches Postgres - env={} is fine here
    because the database is never reached.
    """
    with pytest.raises(UnsupportedScope):
        OpenCodeAdapter().install(scope="global", home=tmp_path, env={})


@pytest.mark.db
def test_a_second_install_overwrites_a_modified_plugin(tmp_path, env):
    """No version marker, unconditional overwrite. remem owns the file."""
    adapter = OpenCodeAdapter()
    adapter.install(scope="user", home=tmp_path, env=env)
    plugin = tmp_path / ".config" / "opencode" / "plugin" / "remem.js"
    plugin.write_text("// someone edited this\n")

    adapter.install(scope="user", home=tmp_path, env=env)

    assert plugin.read_text().startswith("// generated by remem - do not edit")


@pytest.mark.db
def test_the_install_never_touches_opencode_config(tmp_path, env):
    """The plugin directory IS the registration, so there is no user config
    file to merge or corrupt. That is a property worth pinning."""
    config = tmp_path / ".config" / "opencode" / "config.json"
    config.parent.mkdir(parents=True)
    config.write_text('{"model": "anthropic/claude-opus-5"}')

    OpenCodeAdapter().install(scope="user", home=tmp_path, env=env)

    assert config.read_text() == '{"model": "anthropic/claude-opus-5"}'


@pytest.mark.db
def test_the_install_reports_the_opt_in_gate(tmp_path, env):
    """Recording is off until the user enables it per project, and an
    install that does not say so leaves them waiting for events that will
    never come."""
    report = OpenCodeAdapter().install(scope="user", home=tmp_path, env=env)

    assert any("record enable" in note for note in report.notes)


@pytest.mark.db
def test_the_install_folds_in_a_live_verification_round_trip(tmp_path, env):
    """The thing CT-1 exists to catch: install() now calls verify() (Task 6),
    and a test suite that never asserts on the result would not have noticed
    when that round-trip silently failed. Modelled on
    tests/test_claude_code_events_install.py's install-verification tests."""
    report = OpenCodeAdapter().install(scope="user", home=tmp_path, env=env)

    assert any("round-trip" in a for a in report.actions)
    assert report.warnings == []
