"""Writing the plugin, and overwriting it.

remem owns plugin.js: no version marker, no merge, no prompt. The file is
machine-generated and machine-replaced, and the install says where it went.
"""

from __future__ import annotations

import pytest

from remem.agents.base import UnsupportedScope
from remem.agents.opencode.adapter import OpenCodeAdapter


def test_user_scope_writes_the_plugin_under_the_config_directory(tmp_path):
    report = OpenCodeAdapter().install(scope="user", home=tmp_path, env={})

    plugin = tmp_path / ".config" / "opencode" / "plugin" / "remem.js"
    assert plugin.exists()
    assert plugin.read_text().startswith("// generated by remem - do not edit")
    assert any(str(plugin) in action for action in report.actions)


def test_project_scope_writes_beside_the_repository(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    OpenCodeAdapter().install(scope="project", home=tmp_path, env={})

    assert (tmp_path / ".opencode" / "plugin" / "remem.js").exists()


def test_an_unknown_scope_refuses_rather_than_guessing(tmp_path):
    """UnsupportedScope over a fallback: an install that reports success
    while having written somewhere else is worse than one that refuses."""
    with pytest.raises(UnsupportedScope):
        OpenCodeAdapter().install(scope="global", home=tmp_path, env={})


def test_a_second_install_overwrites_a_modified_plugin(tmp_path):
    """No version marker, unconditional overwrite. remem owns the file."""
    adapter = OpenCodeAdapter()
    adapter.install(scope="user", home=tmp_path, env={})
    plugin = tmp_path / ".config" / "opencode" / "plugin" / "remem.js"
    plugin.write_text("// someone edited this\n")

    adapter.install(scope="user", home=tmp_path, env={})

    assert plugin.read_text().startswith("// generated by remem - do not edit")


def test_the_install_never_touches_opencode_config(tmp_path):
    """The plugin directory IS the registration, so there is no user config
    file to merge or corrupt. That is a property worth pinning."""
    config = tmp_path / ".config" / "opencode" / "config.json"
    config.parent.mkdir(parents=True)
    config.write_text('{"model": "anthropic/claude-opus-5"}')

    OpenCodeAdapter().install(scope="user", home=tmp_path, env={})

    assert config.read_text() == '{"model": "anthropic/claude-opus-5"}'


def test_the_install_reports_the_opt_in_gate(tmp_path):
    """Recording is off until the user enables it per project, and an
    install that does not say so leaves them waiting for events that will
    never come."""
    report = OpenCodeAdapter().install(scope="user", home=tmp_path, env={})

    assert any("record enable" in note for note in report.notes)
