"""The portability seam. One implementation today (Postgres); a file backend
would implement this same protocol."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from remem.domain import (
    CaptureJob,
    CaptureStatus,
    Collection,
    Entry,
    Event,
    ExtractJob,
    Hit,
    JobStatus,
    Principal,
    Query,
    SessionRef,
)


class NotOwner(PermissionError):
    """A write targeted a row that belongs to a different principal.

    Ownership is enforced in the store, not left to callers: a backend that
    silently rewrote another principal's row would be an integrity hole no
    service-layer check could close.
    """


class Store(Protocol):
    # principals
    def ensure_principal(self, handle: str) -> Principal: ...
    def get_principal(self, handle: str) -> Principal | None: ...

    # entries
    def put_entry(self, entry: Entry) -> Entry: ...
    def get_entry(self, entry_id: UUID, owner_id: UUID) -> Entry | None: ...
    def set_superseded(self, old_id: UUID, new_entry_id: UUID, owner_id: UUID) -> bool: ...
    def search(self, query: Query, owner_id: UUID) -> list[Hit]: ...
    def fuzzy_search(
        self, query: Query, owner_id: UUID, threshold: float
    ) -> list[Hit]: ...

    # vectors
    def put_vector(
        self, entry_id: UUID, model: str, dim: int,
        vector: list[float], owner_id: UUID,
    ) -> None: ...
    def entries_missing_vectors(
        self, owner_id: UUID, model: str, limit: int
    ) -> list[Entry]: ...
    def semantic_search(
        self, query: Query, owner_id: UUID, vector: list[float],
        model: str, threshold: float,
    ) -> list[Hit]: ...

    # collections
    def put_collection(self, collection: Collection) -> Collection: ...
    def get_collection(self, slug: str, owner_id: UUID) -> Collection | None: ...
    def list_collections(self, owner_id: UUID) -> list[Collection]: ...
    def pin(
        self, collection_id: UUID, entry_id: UUID, position: int, owner_id: UUID
    ) -> None: ...
    def pinned_entries(self, collection_id: UUID, owner_id: UUID) -> list[Entry]: ...

    # capture
    def set_record_enabled(self, owner_id: UUID, project: str, enabled: bool) -> None: ...
    def record_enabled(self, owner_id: UUID, project: str) -> bool: ...
    def enqueue_capture(self, job: CaptureJob) -> CaptureJob: ...
    def claim_capture_jobs(self, owner_id: UUID, limit: int, stale_after_seconds: int = 600) -> list[CaptureJob]: ...
    def claim_capture_job(self, job_id: UUID, owner_id: UUID) -> CaptureJob | None: ...
    def finish_capture_job(self, job_id: UUID, owner_id: UUID, status: CaptureStatus, error: str | None, entries_written: int) -> None: ...
    def get_capture_job(self, job_id: UUID, owner_id: UUID) -> CaptureJob | None: ...
    def capture_job_counts(self, owner_id: UUID) -> dict[str, int]: ...
    def recent_failed_capture_jobs(self, owner_id: UUID, limit: int = 5) -> list[CaptureJob]: ...
    def enabled_record_projects(self, owner_id: UUID) -> list[str]: ...

    # events
    def put_event(self, event: Event) -> Event: ...
    def events_for_session(
        self, owner_id: UUID, project: str, harness: str, session_id: str,
        since: datetime | None = None, limit: int = 500,
    ) -> list[Event]: ...
    def link_entry_events(
        self, entry_id: UUID, events: list[Event], owner_id: UUID
    ) -> None: ...
    def provenance(
        self, entry_id: UUID, owner_id: UUID
    ) -> list[tuple[UUID, str, str, bool]]: ...

    # extraction spool
    def sessions_awaiting_extraction(
        self, owner_id: UUID, idle_seconds: int, limit: int
    ) -> list[SessionRef]: ...
    def claim_extract_job(self, owner_id: UUID, session: SessionRef) -> ExtractJob: ...
    def claim_extract_job_by_id(
        self, job_id: UUID, owner_id: UUID
    ) -> ExtractJob | None: ...
    def finish_extract_job(
        self, job_id: UUID, owner_id: UUID, status: JobStatus,
        error: str | None, entries_written: int,
        covers_through: datetime | None,
    ) -> None: ...
    def get_extract_job(self, job_id: UUID, owner_id: UUID) -> ExtractJob | None: ...
    def extract_job_counts(self, owner_id: UUID) -> dict[str, int]: ...
    def recent_failed_extract_jobs(
        self, owner_id: UUID, limit: int = 5
    ) -> list[ExtractJob]: ...
    def try_advisory_lock(self, name: str, owner_id: UUID) -> bool: ...
