"""The generated Cursor rules file, and the git hygiene around it.

Cursor cannot be handed context on stdout - its hookSpecificOutput
compatibility covers PreToolUse permission decisions only, with no
additionalContext path - so a file in the workspace is the only way in.
That makes this the first place remem writes context into the user's
working tree rather than into a stream, which is why the git half of this
module exists at all.
"""

from __future__ import annotations

from pathlib import Path

#: Relative to the workspace root. Also the line written to
#: .git/info/exclude, which is why it is spelled with forward slashes.
RULES_PATH = ".cursor/rules/remem.mdc"

#: alwaysApply is what makes Cursor include the rule in every chat in the
#: workspace without the user naming it. The description is what Cursor
#: shows in its rules list.
_FRONTMATTER = """\
---
description: remem knowledge base
alwaysApply: true
---

<!-- generated by remem - do not edit. Rewritten at every session start. -->

"""


def render(block: str) -> str:
    """The .mdc file's full text for one context block."""
    return _FRONTMATTER + block


def write(root: Path, block: str) -> Path:
    """Write the rules file under `root`, overwriting unconditionally.

    Machine-owned, like opencode's remem.js: no merge, no version marker,
    no prompt. A user who wants local edits to it is asking for the wrong
    file.
    """
    path = root / RULES_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(block))
    return path


def exclude(root: Path) -> bool:
    """Add the rules file to .git/info/exclude. True if it added the line.

    .git/info/exclude rather than .gitignore, deliberately. .gitignore is
    tracked, reviewed and merged - appending to it hands the user a diff
    they did not ask for, and in a shared repository that lands in
    somebody's pull request. .git/info/exclude is local-only, needs no
    commit, and is exactly the mechanism git provides for "ignore this
    here, not for everyone".

    What this prevents is the .mdc being committed, which matters because
    its content is one user's knowledge base rendered at one moment:
    publishing it publishes personal notes, and it is stale the moment the
    knowledge base changes.

    Returns False, not an error, when there is no repository - a workspace
    outside one is an ordinary thing.
    """
    info = root / ".git" / "info"
    if not info.parent.is_dir():
        return False
    info.mkdir(parents=True, exist_ok=True)
    target = info / "exclude"

    existing = target.read_text() if target.exists() else ""
    if RULES_PATH in existing.split():
        return False

    prefix = "" if existing == "" or existing.endswith("\n") else "\n"
    target.write_text(f"{existing}{prefix}{RULES_PATH}\n")
    return True
