// generated by remem - do not edit. `remem install opencode`
// overwrites this file unconditionally.
//
// A marshaller and nothing else: it shapes opencode's hook arguments into
// JSON and hands them to the `remem` CLI, which decides everything. It
// imports nothing - `$` arrives on PluginInput - so there is no npm
// dependency to install, to pin, or to keep in step with this file.

const RECORD_TIMEOUT_MS = 5000;
const CONTEXT_TIMEOUT_MS = 10000;

// Sessions whose knowledge base block has already been injected.
//
// This is the one policy decision that lives in the JavaScript, and it is
// here under protest: experimental.chat.system.transform fires on EVERY
// message, opencode has no session-start hook, and per-process state has
// nowhere else to live. Claude Code gets once-per-session semantics from
// its harness; opencode has to be given them.
//
// It dies with the process, which is the correct lifetime: a restarted
// opencode is a new session's worth of context anyway.
const injected = new Set();

// Run a command, feed it JSON on stdin, and give up after `timeoutMs`.
//
// The timeout is a race, not a kill: Bun's ShellPromise cannot be
// cancelled, so a hung `remem` may outlive this call. That is deliberate.
// What must never happen is the user's turn hanging on a knowledge tool,
// and returning on schedule is what prevents it.
//
// Every failure - including JSON.stringify - is swallowed inside the try
// block. This is the same fail-soft contract the Python hooks hold, except
// that nothing here inherits a harness timeout, so the plugin has to impose
// its own. The serialisation must run inside the try, not before it.
async function callRemem($, args, stdinData, timeoutMs) {
  let timer;
  try {
    const stdinText = JSON.stringify(stdinData);
    const running = $`remem ${args} < ${new Response(stdinText)}`
      .quiet()
      .nothrow();
    // If the timeout wins the race below, `running` is abandoned - nothing
    // ever awaits it again. `.nothrow()` means a nonzero exit resolves
    // rather than rejects, so this covers the unlikely remainder: a Bun
    // shell failure that rejects anyway (e.g. `remem` missing from PATH).
    // An abandoned promise that later rejects with no handler is an
    // unhandled rejection, which is exactly the class of crash the
    // fail-soft contract exists to prevent - so give it a no-op catch
    // purely to keep it from ever surfacing as one. The timeout-as-race
    // behaviour is unchanged: a ShellPromise cannot be cancelled, and nobody
    // pretends this makes the underlying `remem` process stop running.
    running.catch(() => {});
    const timeout = new Promise((resolve) => {
      timer = setTimeout(() => resolve(null), timeoutMs);
    });
    const result = await Promise.race([running, timeout]);
    if (result === null) return null;
    return result.exitCode === 0 ? result.stdout.toString() : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

async function record($, cwd, payload) {
  await callRemem(
    $,
    ["record", "event", "--agent", "opencode"],
    { ...payload, cwd },
    RECORD_TIMEOUT_MS,
  );
}

export const server = async ({ $, directory, worktree }) => {
  // `worktree` is the repository root when there is one; `directory` is
  // where the session was started. Either is fine - remem resolves the
  // project through the git common directory on the Python side, so a
  // subdirectory and a worktree file under the same repository - and
  // preferring worktree just means the common case does less work.
  const cwd = worktree || directory;

  return {
    "tool.execute.after": async (input, output) => {
      await record($, cwd, {
        hook: "tool.execute.after",
        sessionID: input.sessionID,
        tool: input.tool,
        callID: input.callID,
        args: input.args,
        result: {
          title: output.title,
          output: output.output,
          metadata: output.metadata,
        },
      });
    },

    "chat.message": async (input, output) => {
      await record($, cwd, {
        hook: "chat.message",
        sessionID: input.sessionID,
        agent: input.agent,
        model: input.model,
        messageID: input.messageID,
        message: output.message,
        parts: output.parts,
      });
    },

    "experimental.chat.system.transform": async (input, output) => {
      // Once per session. A memory written mid-session is therefore not
      // visible until the next one - the same bargain the Claude Code
      // SessionStart hook makes. Re-reading every turn is one line's
      // change from here, and is deliberately not made until the per-turn
      // token and database cost has been measured.
      const id = input.sessionID;
      if (!id || injected.has(id)) return;
      injected.add(id);

      const block = await callRemem(
        $,
        ["hook", "context", "--agent", "opencode"],
        { sessionID: id, cwd },
        CONTEXT_TIMEOUT_MS,
      );
      if (block && block.trim()) output.system.push(block.trim());
    },
  };
};
